# Generated by Django 5.2.2 on 2025-06-09 16:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='BookingModel',
            new_name='Booking',
        ),
        migrations.RenameModel(
            old_name='MenuModel',
            new_name='Menu',
        ),
    ]
