# Generated by Django 5.2.2 on 2025-06-10 18:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0003_alter_menu_inventory'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking',
            old_name='bookingdata',
            new_name='booking_date',
        ),
    ]
